apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    app: orchestrator
  template:
    metadata:
      name: orchestrator
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image:  {{ .Values.images.tags.orchestrator }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - --mode=orchestrator
        ports:
        - name: service-port
          protocol: TCP
          containerPort: 5202