imagePullPolicy: IfNotPresent
images:
  tags:
    webserver: endianogino/simple-webserver:1.0
    aggregator: endianogino/aggregator:1.0
    loadbot: endianogino/vegeta-server:1.0
cpuRequests:
  loadbot: "100m"
  webserver: "100m"

rbac:
  create: true
  serviceAccountName: default

aggregator:
  maxReplicas: 100
  logLevel: 2

loadbot:
  rate: 1000
  workers: 10
  duration: 1s



